### PR TITLE
fixed altars nodeboxes / textures

### PR DESCRIPTION
**Pull request by Napiophelios**
fixed altars nodeboxes / textures
added marble altars/ textures
fixed redundant recipes
amended the readme file
screenshot

edit: I don't know how I messed that up...
but apparently its two pull requests in one

### CODE REVIEW

**Comment by mootpoint** [comment]
looks great added in, i have an idea for the altars, give me a bit and i will show you

**Comment by mootpoint** [comment]
done check it out

**Comment by Napiophelios** [comment]
I dont really like the marble textures..here are a couple of sets I have made already
I kinda like the third choice myself.
comparison

**Comment by mootpoint** [comment]
Alright let's go with three, submit a pull request and I'll merge.

**Comment by Napiophelios** [comment]
ha ha. I would'nt go overboard with them

I think maybe just 2 altars: the marble altar be locked version and the stone version be plain.
I also think textures sets 1&2 are kinda ugly....I would use the third set.

Should the locked function be compatable with the new keys addition to Minetest?
I was thinking maybe check for a priv instead of having a keys and locks. IDK.

**Comment by mootpoint** [comment]
I just checked if the player can dig there, kinda like a shared chest. That
way griefers can't Rob the church. I like the idea of having both. That if
the stone looks better in my church I can still lock it, and similar with
marble

**Comment by mootpoint** [comment]
oh and i meant lets go with # number 3 not 3 altars :)

**Comment by Napiophelios** [comment]
good choice. Great minds think alike
https://forum.minetest.net/viewtopic.php?t=10177

**Comment by mootpoint** [comment]
that block looks like my noclip viewer :)

'cept you made it first :)

**Comment by Napiophelios** [comment]
no..I think someone else did it way before I did. 
I was so proud of it too it was my first mod :)

**Comment by mootpoint** [comment]
My first mod was a peach tea mod i made with my sister, we never 
published it just ran it on a private server :) it has been long lost

**Comment by mootpoint** [comment]
Did you add that marble texture to git? i dont see it

**Pull request merged**
